### PR TITLE
[#52] fix stack overflow when using alias within same fs

### LINKED ISSUE #52: `stack overflow` panic when using alias within same `fs`
Input:
```
fs cpTest() {
	scratch
	mkfile "/foo" 0o644 "foobar" as foo
	copy foo "/foo" "/bar"
}
```

Error:
```
#1 compiling [cpTest]
runtime: goroutine stack exceeds 1000000000-byte limit
fatal error: stack overflow

runtime stack:
runtime.throw(0x4fc7627, 0xe)
	/usr/local/go/src/runtime/panic.go:617 +0x72
runtime.newstack()
	/usr/local/go/src/runtime/stack.go:1041 +0x6f0
runtime.morestack()
	/usr/local/go/src/runtime/asm_amd64.s:429 +0x8f

goroutine 1 [running]:
runtime.heapBitsSetType(0xc006c21c20, 0x10, 0x10, 0x4d9a6c0)
	/usr/local/go/src/runtime/mbitmap.go:938 +0xa56 fp=0xc024000350 sp=0xc024000348 pc=0x40187b6
runtime.mallocgc(0x10, 0x4d9a6c0, 0x1, 0x0)
	/usr/local/go/src/runtime/malloc.go:969 +0x51c fp=0xc0240003f0 sp=0xc024000350 pc=0x400e37c
runtime.newobject(0x4d9a6c0, 0x0)
	/usr/local/go/src/runtime/malloc.go:1068 +0x38 fp=0xc024000420 sp=0xc0240003f0 pc=0x400e9d8
github.com/moby/buildkit/client/llb.dirf(0x4fbbf46, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	pkg/mod/github.com/hinshun/buildkit@v0.0.0-20200128194027-9973cb02a5b6/client/llb/meta.go:40 +0x31 fp=0xc024000470 sp=0xc024000420 pc=0x438ebb1
github.com/moby/buildkit/client/llb.dir(...)
	pkg/mod/github.com/hinshun/buildkit@v0.0.0-20200128194027-9973cb02a5b6/client/llb/meta.go:37
github.com/moby/buildkit/client/llb.NewState(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	pkg/mod/github.com/hinshun/buildkit@v0.0.0-20200128194027-9973cb02a5b6/client/llb/state.go:37 +0xda fp=0xc024000528 sp=0xc024000470 pc=0x43937da
github.com/moby/buildkit/client/llb.Scratch(...)
	pkg/mod/github.com/hinshun/buildkit@v0.0.0-20200128194027-9973cb02a5b6/client/llb/source.go:243
github.com/openllb/hlb/codegen.(*CodeGen).EmitFilesystemSourceStmt(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0xc000382c40, 0xc003eabc20, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/hlb/codegen/codegen.go:332 +0x14b0 fp=0xc024000878 sp=0xc024000528 pc=0x4c65be0
github.com/openllb/hlb/codegen.(*CodeGen).EmitSourceStmt(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0x4fbc146, 0x2, 0xc000382c40, 0xc000319b66, 0x7, 0xc003eabc20, ...)
	/go/src/hlb/codegen/codegen.go:287 +0x20a fp=0xc024000948 sp=0xc024000878 pc=0x4c6416a
github.com/openllb/hlb/codegen.(*CodeGen).EmitBlock(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0x4fbc146, 0x2, 0xc003eabc40, 0x3, 0x4, 0xc003eabc20, ...)
	/go/src/hlb/codegen/codegen.go:170 +0x31a fp=0xc024000bf0 sp=0xc024000948 pc=0x4c6294a
github.com/openllb/hlb/codegen.(*CodeGen).EmitFilesystemBlock(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0xc003eabc40, 0x3, 0x4, 0xc003eabc20, 0x0, 0x0, ...)
	/go/src/hlb/codegen/codegen.go:253 +0xd7 fp=0xc024000cf0 sp=0xc024000bf0 pc=0x4c63737
github.com/openllb/hlb/codegen.(*CodeGen).EmitFuncDecl(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0xc0004cd9e0, 0x0, 0x0, 0x0, 0xc003eabc20, 0xc0004f0000, ...)
	/go/src/hlb/codegen/decl.go:45 +0x717 fp=0xc024000ea8 sp=0xc024000cf0 pc=0x4c79917
github.com/openllb/hlb/codegen.(*CodeGen).EmitAliasDecl(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0xc0004ce190, 0x0, 0xc0004de138, 0x40ec75a, 0xc0004de0d0, 0x203000)
	/go/src/hlb/codegen/decl.go:81 +0xd7 fp=0xc024000f28 sp=0xc024000ea8 pc=0x4c7a1d7
github.com/openllb/hlb/codegen.(*CodeGen).EmitFilesystemAliasDecl(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0xc0004ce190, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/hlb/codegen/decl.go:94 +0xa8 fp=0xc024001008 sp=0xc024000f28 pc=0x4c7a328
github.com/openllb/hlb/codegen.(*CodeGen).EmitFilesystemExpr(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0x0, 0xc0004ce4b0, 0xc003eabbe0, 0x0, 0x0, 0x0, ...)
	/go/src/hlb/codegen/expr.go:109 +0x3ca fp=0xc024001188 sp=0xc024001008 pc=0x4c7b9da
github.com/openllb/hlb/codegen.(*CodeGen).EmitFilesystemChainStmt(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0x4fbc146, 0x2, 0xc000382e00, 0xc003eabbe0, 0xc0022eb320, 0x0, ...)
	/go/src/hlb/codegen/codegen.go:681 +0x1b87 fp=0xc0240014f8 sp=0xc024001188 pc=0x4c680f7
github.com/openllb/hlb/codegen.(*CodeGen).EmitChainStmt(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0x4fbc146, 0x2, 0xc000382e00, 0xc003eabbe0, 0x0, 0x0, ...)
	/go/src/hlb/codegen/codegen.go:228 +0x9c fp=0xc024001568 sp=0xc0240014f8 pc=0x4c634fc
github.com/openllb/hlb/codegen.(*CodeGen).EmitBlock(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0x4fbc146, 0x2, 0xc003eabc00, 0x3, 0x4, 0xc003eabbe0, ...)
	/go/src/hlb/codegen/codegen.go:203 +0x703 fp=0xc024001810 sp=0xc024001568 pc=0x4c62d33
github.com/openllb/hlb/codegen.(*CodeGen).EmitFilesystemBlock(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0xc003eabc00, 0x3, 0x4, 0xc003eabbe0, 0x0, 0x0, ...)
	/go/src/hlb/codegen/codegen.go:253 +0xd7 fp=0xc024001910 sp=0xc024001810 pc=0x4c63737
github.com/openllb/hlb/codegen.(*CodeGen).EmitFuncDecl(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0xc0004cd9e0, 0x0, 0x0, 0x0, 0xc003eabbe0, 0xc0004f0000, ...)
	/go/src/hlb/codegen/decl.go:45 +0x717 fp=0xc024001ac8 sp=0xc024001910 pc=0x4c79917
github.com/openllb/hlb/codegen.(*CodeGen).EmitAliasDecl(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0xc0004ce190, 0x0, 0xc0004de138, 0x64fffff, 0xc0004de0d0, 0x4017a7a)
	/go/src/hlb/codegen/decl.go:81 +0xd7 fp=0xc024001b48 sp=0xc024001ac8 pc=0x4c7a1d7
github.com/openllb/hlb/codegen.(*CodeGen).EmitFilesystemAliasDecl(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0xc0004ce190, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/hlb/codegen/decl.go:94 +0xa8 fp=0xc024001c28 sp=0xc024001b48 pc=0x4c7a328
github.com/openllb/hlb/codegen.(*CodeGen).EmitFilesystemExpr(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0x0, 0xc0004ce4b0, 0xc003eabba0, 0x0, 0x0, 0x0, ...)
	/go/src/hlb/codegen/expr.go:109 +0x3ca fp=0xc024001da8 sp=0xc024001c28 pc=0x4c7b9da
github.com/openllb/hlb/codegen.(*CodeGen).EmitFilesystemChainStmt(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0x4fbc146, 0x2, 0xc000382e00, 0xc003eabba0, 0xc0022eb0e0, 0x0, ...)
	/go/src/hlb/codegen/codegen.go:681 +0x1b87 fp=0xc024002118 sp=0xc024001da8 pc=0x4c680f7
github.com/openllb/hlb/codegen.(*CodeGen).EmitChainStmt(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0x4fbc146, 0x2, 0xc000382e00, 0xc003eabba0, 0x0, 0x0, ...)
	/go/src/hlb/codegen/codegen.go:228 +0x9c fp=0xc024002188 sp=0xc024002118 pc=0x4c634fc
github.com/openllb/hlb/codegen.(*CodeGen).EmitBlock(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0x4fbc146, 0x2, 0xc003eabbc0, 0x3, 0x4, 0xc003eabba0, ...)
	/go/src/hlb/codegen/codegen.go:203 +0x703 fp=0xc024002430 sp=0xc024002188 pc=0x4c62d33
github.com/openllb/hlb/codegen.(*CodeGen).EmitFilesystemBlock(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0xc003eabbc0, 0x3, 0x4, 0xc003eabba0, 0x0, 0x0, ...)
	/go/src/hlb/codegen/codegen.go:253 +0xd7 fp=0xc024002530 sp=0xc024002430 pc=0x4c63737
github.com/openllb/hlb/codegen.(*CodeGen).EmitFuncDecl(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0xc0004cd9e0, 0x0, 0x0, 0x0, 0xc003eabba0, 0xc0004f0000, ...)
	/go/src/hlb/codegen/decl.go:45 +0x717 fp=0xc0240026e8 sp=0xc024002530 pc=0x4c79917
github.com/openllb/hlb/codegen.(*CodeGen).EmitAliasDecl(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0xc0004ce190, 0x0, 0xc0004de138, 0x40ec75a, 0xc0004de0d0, 0x203000)
	/go/src/hlb/codegen/decl.go:81 +0xd7 fp=0xc024002768 sp=0xc0240026e8 pc=0x4c7a1d7
github.com/openllb/hlb/codegen.(*CodeGen).EmitFilesystemAliasDecl(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0xc0004ce190, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/hlb/codegen/decl.go:94 +0xa8 fp=0xc024002848 sp=0xc024002768 pc=0x4c7a328
github.com/openllb/hlb/codegen.(*CodeGen).EmitFilesystemExpr(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0x0, 0xc0004ce4b0, 0xc003eabb60, 0x0, 0x0, 0x0, ...)
	/go/src/hlb/codegen/expr.go:109 +0x3ca fp=0xc0240029c8 sp=0xc024002848 pc=0x4c7b9da
github.com/openllb/hlb/codegen.(*CodeGen).EmitFilesystemChainStmt(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0x4fbc146, 0x2, 0xc000382e00, 0xc003eabb60, 0xc0022eaea0, 0x0, ...)
	/go/src/hlb/codegen/codegen.go:681 +0x1b87 fp=0xc024002d38 sp=0xc0240029c8 pc=0x4c680f7
github.com/openllb/hlb/codegen.(*CodeGen).EmitChainStmt(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0x4fbc146, 0x2, 0xc000382e00, 0xc003eabb60, 0x0, 0x0, ...)
	/go/src/hlb/codegen/codegen.go:228 +0x9c fp=0xc024002da8 sp=0xc024002d38 pc=0x4c634fc
github.com/openllb/hlb/codegen.(*CodeGen).EmitBlock(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0x4fbc146, 0x2, 0xc003eabb80, 0x3, 0x4, 0xc003eabb60, ...)
	/go/src/hlb/codegen/codegen.go:203 +0x703 fp=0xc024003050 sp=0xc024002da8 pc=0x4c62d33
github.com/openllb/hlb/codegen.(*CodeGen).EmitFilesystemBlock(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0xc003eabb80, 0x3, 0x4, 0xc003eabb60, 0x0, 0x0, ...)
	/go/src/hlb/codegen/codegen.go:253 +0xd7 fp=0xc024003150 sp=0xc024003050 pc=0x4c63737
github.com/openllb/hlb/codegen.(*CodeGen).EmitFuncDecl(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0xc0004cd9e0, 0x0, 0x0, 0x0, 0xc003eabb60, 0xc0004f0000, ...)
	/go/src/hlb/codegen/decl.go:45 +0x717 fp=0xc024003308 sp=0xc024003150 pc=0x4c79917
github.com/openllb/hlb/codegen.(*CodeGen).EmitAliasDecl(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0xc0004ce190, 0x0, 0xc0004de138, 0x40ec75a, 0xc0004de0d0, 0x203000)
	/go/src/hlb/codegen/decl.go:81 +0xd7 fp=0xc024003388 sp=0xc024003308 pc=0x4c7a1d7
github.com/openllb/hlb/codegen.(*CodeGen).EmitFilesystemAliasDecl(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0xc0004ce190, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/hlb/codegen/decl.go:94 +0xa8 fp=0xc024003468 sp=0xc024003388 pc=0x4c7a328
github.com/openllb/hlb/codegen.(*CodeGen).EmitFilesystemExpr(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0x0, 0xc0004ce4b0, 0xc003eabb20, 0x0, 0x0, 0x0, ...)
	/go/src/hlb/codegen/expr.go:109 +0x3ca fp=0xc0240035e8 sp=0xc024003468 pc=0x4c7b9da
github.com/openllb/hlb/codegen.(*CodeGen).EmitFilesystemChainStmt(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0x4fbc146, 0x2, 0xc000382e00, 0xc003eabb20, 0xc0022eac60, 0x0, ...)
	/go/src/hlb/codegen/codegen.go:681 +0x1b87 fp=0xc024003958 sp=0xc0240035e8 pc=0x4c680f7
github.com/openllb/hlb/codegen.(*CodeGen).EmitChainStmt(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0x4fbc146, 0x2, 0xc000382e00, 0xc003eabb20, 0x0, 0x0, ...)
	/go/src/hlb/codegen/codegen.go:228 +0x9c fp=0xc0240039c8 sp=0xc024003958 pc=0x4c634fc
github.com/openllb/hlb/codegen.(*CodeGen).EmitBlock(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0x4fbc146, 0x2, 0xc003eabb40, 0x3, 0x4, 0xc003eabb20, ...)
	/go/src/hlb/codegen/codegen.go:203 +0x703 fp=0xc024003c70 sp=0xc0240039c8 pc=0x4c62d33
github.com/openllb/hlb/codegen.(*CodeGen).EmitFilesystemBlock(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0xc003eabb40, 0x3, 0x4, 0xc003eabb20, 0x0, 0x0, ...)
	/go/src/hlb/codegen/codegen.go:253 +0xd7 fp=0xc024003d70 sp=0xc024003c70 pc=0x4c63737
github.com/openllb/hlb/codegen.(*CodeGen).EmitFuncDecl(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0xc0004cd9e0, 0x0, 0x0, 0x0, 0xc003eabb20, 0xc0004f0000, ...)
	/go/src/hlb/codegen/decl.go:45 +0x717 fp=0xc024003f28 sp=0xc024003d70 pc=0x4c79917
github.com/openllb/hlb/codegen.(*CodeGen).EmitAliasDecl(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0xc0004ce190, 0x0, 0xc0004de138, 0x40ec75a, 0xc0004de0d0, 0x203000)
	/go/src/hlb/codegen/decl.go:81 +0xd7 fp=0xc024003fa8 sp=0xc024003f28 pc=0x4c7a1d7
github.com/openllb/hlb/codegen.(*CodeGen).EmitFilesystemAliasDecl(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0xc0004ce190, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/hlb/codegen/decl.go:94 +0xa8 fp=0xc024004088 sp=0xc024003fa8 pc=0x4c7a328
github.com/openllb/hlb/codegen.(*CodeGen).EmitFilesystemExpr(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0x0, 0xc0004ce4b0, 0xc003eabae0, 0x0, 0x0, 0x0, ...)
	/go/src/hlb/codegen/expr.go:109 +0x3ca fp=0xc024004208 sp=0xc024004088 pc=0x4c7b9da
github.com/openllb/hlb/codegen.(*CodeGen).EmitFilesystemChainStmt(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0x4fbc146, 0x2, 0xc000382e00, 0xc003eabae0, 0xc0022eaa20, 0x0, ...)
	/go/src/hlb/codegen/codegen.go:681 +0x1b87 fp=0xc024004578 sp=0xc024004208 pc=0x4c680f7
github.com/openllb/hlb/codegen.(*CodeGen).EmitChainStmt(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0x4fbc146, 0x2, 0xc000382e00, 0xc003eabae0, 0x0, 0x0, ...)
	/go/src/hlb/codegen/codegen.go:228 +0x9c fp=0xc0240045e8 sp=0xc024004578 pc=0x4c634fc
github.com/openllb/hlb/codegen.(*CodeGen).EmitBlock(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0x4fbc146, 0x2, 0xc003eabb00, 0x3, 0x4, 0xc003eabae0, ...)
	/go/src/hlb/codegen/codegen.go:203 +0x703 fp=0xc024004890 sp=0xc0240045e8 pc=0x4c62d33
github.com/openllb/hlb/codegen.(*CodeGen).EmitFilesystemBlock(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0xc003eabb00, 0x3, 0x4, 0xc003eabae0, 0x0, 0x0, ...)
	/go/src/hlb/codegen/codegen.go:253 +0xd7 fp=0xc024004990 sp=0xc024004890 pc=0x4c63737
github.com/openllb/hlb/codegen.(*CodeGen).EmitFuncDecl(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0xc0004cd9e0, 0x0, 0x0, 0x0, 0xc003eabae0, 0xc0004f0000, ...)
	/go/src/hlb/codegen/decl.go:45 +0x717 fp=0xc024004b48 sp=0xc024004990 pc=0x4c79917
github.com/openllb/hlb/codegen.(*CodeGen).EmitAliasDecl(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0xc0004ce190, 0x0, 0xc0004de138, 0x40ec75a, 0xc0004de0d0, 0x203000)
	/go/src/hlb/codegen/decl.go:81 +0xd7 fp=0xc024004bc8 sp=0xc024004b48 pc=0x4c7a1d7
github.com/openllb/hlb/codegen.(*CodeGen).EmitFilesystemAliasDecl(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0xc0004ce190, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/hlb/codegen/decl.go:94 +0xa8 fp=0xc024004ca8 sp=0xc024004bc8 pc=0x4c7a328
github.com/openllb/hlb/codegen.(*CodeGen).EmitFilesystemExpr(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0x0, 0xc0004ce4b0, 0xc003eabaa0, 0x0, 0x0, 0x0, ...)
	/go/src/hlb/codegen/expr.go:109 +0x3ca fp=0xc024004e28 sp=0xc024004ca8 pc=0x4c7b9da
github.com/openllb/hlb/codegen.(*CodeGen).EmitFilesystemChainStmt(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0x4fbc146, 0x2, 0xc000382e00, 0xc003eabaa0, 0xc0022ea7e0, 0x0, ...)
	/go/src/hlb/codegen/codegen.go:681 +0x1b87 fp=0xc024005198 sp=0xc024004e28 pc=0x4c680f7
github.com/openllb/hlb/codegen.(*CodeGen).EmitChainStmt(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0x4fbc146, 0x2, 0xc000382e00, 0xc003eabaa0, 0x0, 0x0, ...)
	/go/src/hlb/codegen/codegen.go:228 +0x9c fp=0xc024005208 sp=0xc024005198 pc=0x4c634fc
github.com/openllb/hlb/codegen.(*CodeGen).EmitBlock(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0x4fbc146, 0x2, 0xc003eabac0, 0x3, 0x4, 0xc003eabaa0, ...)
	/go/src/hlb/codegen/codegen.go:203 +0x703 fp=0xc0240054b0 sp=0xc024005208 pc=0x4c62d33
github.com/openllb/hlb/codegen.(*CodeGen).EmitFilesystemBlock(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0xc003eabac0, 0x3, 0x4, 0xc003eabaa0, 0x0, 0x0, ...)
	/go/src/hlb/codegen/codegen.go:253 +0xd7 fp=0xc0240055b0 sp=0xc0240054b0 pc=0x4c63737
github.com/openllb/hlb/codegen.(*CodeGen).EmitFuncDecl(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0xc0004cd9e0, 0x0, 0x0, 0x0, 0xc003eabaa0, 0xc0004f0000, ...)
	/go/src/hlb/codegen/decl.go:45 +0x717 fp=0xc024005768 sp=0xc0240055b0 pc=0x4c79917
github.com/openllb/hlb/codegen.(*CodeGen).EmitAliasDecl(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0xc0004ce190, 0x0, 0xc0004de138, 0x40ec75a, 0xc0004de0d0, 0x203000)
	/go/src/hlb/codegen/decl.go:81 +0xd7 fp=0xc0240057e8 sp=0xc024005768 pc=0x4c7a1d7
github.com/openllb/hlb/codegen.(*CodeGen).EmitFilesystemAliasDecl(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0xc0004ce190, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/hlb/codegen/decl.go:94 +0xa8 fp=0xc0240058c8 sp=0xc0240057e8 pc=0x4c7a328
github.com/openllb/hlb/codegen.(*CodeGen).EmitFilesystemExpr(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0x0, 0xc0004ce4b0, 0xc003eaba60, 0x0, 0x0, 0x0, ...)
	/go/src/hlb/codegen/expr.go:109 +0x3ca fp=0xc024005a48 sp=0xc0240058c8 pc=0x4c7b9da
github.com/openllb/hlb/codegen.(*CodeGen).EmitFilesystemChainStmt(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0x4fbc146, 0x2, 0xc000382e00, 0xc003eaba60, 0xc0022ea5a0, 0x0, ...)
	/go/src/hlb/codegen/codegen.go:681 +0x1b87 fp=0xc024005db8 sp=0xc024005a48 pc=0x4c680f7
github.com/openllb/hlb/codegen.(*CodeGen).EmitChainStmt(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0x4fbc146, 0x2, 0xc000382e00, 0xc003eaba60, 0x0, 0x0, ...)
	/go/src/hlb/codegen/codegen.go:228 +0x9c fp=0xc024005e28 sp=0xc024005db8 pc=0x4c634fc
github.com/openllb/hlb/codegen.(*CodeGen).EmitBlock(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0x4fbc146, 0x2, 0xc003eaba80, 0x3, 0x4, 0xc003eaba60, ...)
	/go/src/hlb/codegen/codegen.go:203 +0x703 fp=0xc0240060d0 sp=0xc024005e28 pc=0x4c62d33
github.com/openllb/hlb/codegen.(*CodeGen).EmitFilesystemBlock(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0xc003eaba80, 0x3, 0x4, 0xc003eaba60, 0x0, 0x0, ...)
	/go/src/hlb/codegen/codegen.go:253 +0xd7 fp=0xc0240061d0 sp=0xc0240060d0 pc=0x4c63737
github.com/openllb/hlb/codegen.(*CodeGen).EmitFuncDecl(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0xc0004cd9e0, 0x0, 0x0, 0x0, 0xc003eaba60, 0xc0004f0000, ...)
	/go/src/hlb/codegen/decl.go:45 +0x717 fp=0xc024006388 sp=0xc0240061d0 pc=0x4c79917
github.com/openllb/hlb/codegen.(*CodeGen).EmitAliasDecl(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0xc0004ce190, 0x0, 0xc0004de138, 0x40ec75a, 0xc0004de0d0, 0x203000)
	/go/src/hlb/codegen/decl.go:81 +0xd7 fp=0xc024006408 sp=0xc024006388 pc=0x4c7a1d7
github.com/openllb/hlb/codegen.(*CodeGen).EmitFilesystemAliasDecl(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0xc0004ce190, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/hlb/codegen/decl.go:94 +0xa8 fp=0xc0240064e8 sp=0xc024006408 pc=0x4c7a328
github.com/openllb/hlb/codegen.(*CodeGen).EmitFilesystemExpr(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0x0, 0xc0004ce4b0, 0xc003eaba20, 0x0, 0x0, 0x0, ...)
	/go/src/hlb/codegen/expr.go:109 +0x3ca fp=0xc024006668 sp=0xc0240064e8 pc=0x4c7b9da
github.com/openllb/hlb/codegen.(*CodeGen).EmitFilesystemChainStmt(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0x4fbc146, 0x2, 0xc000382e00, 0xc003eaba20, 0xc0022ea360, 0x0, ...)
	/go/src/hlb/codegen/codegen.go:681 +0x1b87 fp=0xc0240069d8 sp=0xc024006668 pc=0x4c680f7
github.com/openllb/hlb/codegen.(*CodeGen).EmitChainStmt(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0x4fbc146, 0x2, 0xc000382e00, 0xc003eaba20, 0x0, 0x0, ...)
	/go/src/hlb/codegen/codegen.go:228 +0x9c fp=0xc024006a48 sp=0xc0240069d8 pc=0x4c634fc
github.com/openllb/hlb/codegen.(*CodeGen).EmitBlock(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0x4fbc146, 0x2, 0xc003eaba40, 0x3, 0x4, 0xc003eaba20, ...)
	/go/src/hlb/codegen/codegen.go:203 +0x703 fp=0xc024006cf0 sp=0xc024006a48 pc=0x4c62d33
github.com/openllb/hlb/codegen.(*CodeGen).EmitFilesystemBlock(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0xc003eaba40, 0x3, 0x4, 0xc003eaba20, 0x0, 0x0, ...)
	/go/src/hlb/codegen/codegen.go:253 +0xd7 fp=0xc024006df0 sp=0xc024006cf0 pc=0x4c63737
github.com/openllb/hlb/codegen.(*CodeGen).EmitFuncDecl(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0xc0004cd9e0, 0x0, 0x0, 0x0, 0xc003eaba20, 0xc0004f0000, ...)
	/go/src/hlb/codegen/decl.go:45 +0x717 fp=0xc024006fa8 sp=0xc024006df0 pc=0x4c79917
github.com/openllb/hlb/codegen.(*CodeGen).EmitAliasDecl(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0xc0004ce190, 0x0, 0xc0004de138, 0x40ec75a, 0xc0004de0d0, 0x203000)
	/go/src/hlb/codegen/decl.go:81 +0xd7 fp=0xc024007028 sp=0xc024006fa8 pc=0x4c7a1d7
github.com/openllb/hlb/codegen.(*CodeGen).EmitFilesystemAliasDecl(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0xc0004ce190, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/hlb/codegen/decl.go:94 +0xa8 fp=0xc024007108 sp=0xc024007028 pc=0x4c7a328
github.com/openllb/hlb/codegen.(*CodeGen).EmitFilesystemExpr(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0x0, 0xc0004ce4b0, 0xc003eab9e0, 0x0, 0x0, 0x0, ...)
	/go/src/hlb/codegen/expr.go:109 +0x3ca fp=0xc024007288 sp=0xc024007108 pc=0x4c7b9da
github.com/openllb/hlb/codegen.(*CodeGen).EmitFilesystemChainStmt(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0x4fbc146, 0x2, 0xc000382e00, 0xc003eab9e0, 0xc0022ea120, 0x0, ...)
	/go/src/hlb/codegen/codegen.go:681 +0x1b87 fp=0xc0240075f8 sp=0xc024007288 pc=0x4c680f7
github.com/openllb/hlb/codegen.(*CodeGen).EmitChainStmt(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0x4fbc146, 0x2, 0xc000382e00, 0xc003eab9e0, 0x0, 0x0, ...)
	/go/src/hlb/codegen/codegen.go:228 +0x9c fp=0xc024007668 sp=0xc0240075f8 pc=0x4c634fc
github.com/openllb/hlb/codegen.(*CodeGen).EmitBlock(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0x4fbc146, 0x2, 0xc003eaba00, 0x3, 0x4, 0xc003eab9e0, ...)
	/go/src/hlb/codegen/codegen.go:203 +0x703 fp=0xc024007910 sp=0xc024007668 pc=0x4c62d33
github.com/openllb/hlb/codegen.(*CodeGen).EmitFilesystemBlock(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0xc003eaba00, 0x3, 0x4, 0xc003eab9e0, 0x0, 0x0, ...)
	/go/src/hlb/codegen/codegen.go:253 +0xd7 fp=0xc024007a10 sp=0xc024007910 pc=0x4c63737
github.com/openllb/hlb/codegen.(*CodeGen).EmitFuncDecl(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0xc0004cd9e0, 0x0, 0x0, 0x0, 0xc003eab9e0, 0xc0004f0000, ...)
	/go/src/hlb/codegen/decl.go:45 +0x717 fp=0xc024007bc8 sp=0xc024007a10 pc=0x4c79917
github.com/openllb/hlb/codegen.(*CodeGen).EmitAliasDecl(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0xc0004ce190, 0x0, 0xc0004de138, 0x40ec75a, 0xc0004de0d0, 0x203000)
	/go/src/hlb/codegen/decl.go:81 +0xd7 fp=0xc024007c48 sp=0xc024007bc8 pc=0x4c7a1d7
github.com/openllb/hlb/codegen.(*CodeGen).EmitFilesystemAliasDecl(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0xc0004ce190, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/hlb/codegen/decl.go:94 +0xa8 fp=0xc024007d28 sp=0xc024007c48 pc=0x4c7a328
github.com/openllb/hlb/codegen.(*CodeGen).EmitFilesystemExpr(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0x0, 0xc0004ce4b0, 0xc003eab9a0, 0x0, 0x0, 0x0, ...)
	/go/src/hlb/codegen/expr.go:109 +0x3ca fp=0xc024007ea8 sp=0xc024007d28 pc=0x4c7b9da
github.com/openllb/hlb/codegen.(*CodeGen).EmitFilesystemChainStmt(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0x4fbc146, 0x2, 0xc000382e00, 0xc003eab9a0, 0xc0022e3ec0, 0x0, ...)
	/go/src/hlb/codegen/codegen.go:681 +0x1b87 fp=0xc024008218 sp=0xc024007ea8 pc=0x4c680f7
github.com/openllb/hlb/codegen.(*CodeGen).EmitChainStmt(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0x4fbc146, 0x2, 0xc000382e00, 0xc003eab9a0, 0x0, 0x0, ...)
	/go/src/hlb/codegen/codegen.go:228 +0x9c fp=0xc024008288 sp=0xc024008218 pc=0x4c634fc
github.com/openllb/hlb/codegen.(*CodeGen).EmitBlock(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0x4fbc146, 0x2, 0xc003eab9c0, 0x3, 0x4, 0xc003eab9a0, ...)
	/go/src/hlb/codegen/codegen.go:203 +0x703 fp=0xc024008530 sp=0xc024008288 pc=0x4c62d33
github.com/openllb/hlb/codegen.(*CodeGen).EmitFilesystemBlock(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0xc003eab9c0, 0x3, 0x4, 0xc003eab9a0, 0x0, 0x0, ...)
	/go/src/hlb/codegen/codegen.go:253 +0xd7 fp=0xc024008630 sp=0xc024008530 pc=0x4c63737
github.com/openllb/hlb/codegen.(*CodeGen).EmitFuncDecl(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0xc0004cd9e0, 0x0, 0x0, 0x0, 0xc003eab9a0, 0xc0004f0000, ...)
	/go/src/hlb/codegen/decl.go:45 +0x717 fp=0xc0240087e8 sp=0xc024008630 pc=0x4c79917
github.com/openllb/hlb/codegen.(*CodeGen).EmitAliasDecl(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0xc0004ce190, 0x0, 0xc0004de138, 0x40ec75a, 0xc0004de0d0, 0x203000)
	/go/src/hlb/codegen/decl.go:81 +0xd7 fp=0xc024008868 sp=0xc0240087e8 pc=0x4c7a1d7
github.com/openllb/hlb/codegen.(*CodeGen).EmitFilesystemAliasDecl(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0xc0004ce190, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/hlb/codegen/decl.go:94 +0xa8 fp=0xc024008948 sp=0xc024008868 pc=0x4c7a328
github.com/openllb/hlb/codegen.(*CodeGen).EmitFilesystemExpr(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0x0, 0xc0004ce4b0, 0xc003eab960, 0x0, 0x0, 0x0, ...)
	/go/src/hlb/codegen/expr.go:109 +0x3ca fp=0xc024008ac8 sp=0xc024008948 pc=0x4c7b9da
github.com/openllb/hlb/codegen.(*CodeGen).EmitFilesystemChainStmt(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0x4fbc146, 0x2, 0xc000382e00, 0xc003eab960, 0xc0022e3c80, 0x0, ...)
	/go/src/hlb/codegen/codegen.go:681 +0x1b87 fp=0xc024008e38 sp=0xc024008ac8 pc=0x4c680f7
github.com/openllb/hlb/codegen.(*CodeGen).EmitChainStmt(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0x4fbc146, 0x2, 0xc000382e00, 0xc003eab960, 0x0, 0x0, ...)
	/go/src/hlb/codegen/codegen.go:228 +0x9c fp=0xc024008ea8 sp=0xc024008e38 pc=0x4c634fc
github.com/openllb/hlb/codegen.(*CodeGen).EmitBlock(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0x4fbc146, 0x2, 0xc003eab980, 0x3, 0x4, 0xc003eab960, ...)
	/go/src/hlb/codegen/codegen.go:203 +0x703 fp=0xc024009150 sp=0xc024008ea8 pc=0x4c62d33
github.com/openllb/hlb/codegen.(*CodeGen).EmitFilesystemBlock(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0xc003eab980, 0x3, 0x4, 0xc003eab960, 0x0, 0x0, ...)
	/go/src/hlb/codegen/codegen.go:253 +0xd7 fp=0xc024009250 sp=0xc024009150 pc=0x4c63737
github.com/openllb/hlb/codegen.(*CodeGen).EmitFuncDecl(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0xc0004cd9e0, 0x0, 0x0, 0x0, 0xc003eab960, 0xc0004f0000, ...)
	/go/src/hlb/codegen/decl.go:45 +0x717 fp=0xc024009408 sp=0xc024009250 pc=0x4c79917
github.com/openllb/hlb/codegen.(*CodeGen).EmitAliasDecl(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0xc0004ce190, 0x0, 0xc0004de138, 0x40ec75a, 0xc0004de0d0, 0x203000)
	/go/src/hlb/codegen/decl.go:81 +0xd7 fp=0xc024009488 sp=0xc024009408 pc=0x4c7a1d7
github.com/openllb/hlb/codegen.(*CodeGen).EmitFilesystemAliasDecl(0xc00047e000, 0x51bee80, 0xc0003882c0, 0xc0004d2d80, 0xc0004ce190, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/hlb/codegen/decl.go:94 +0xa8 fp=0xc024009568 sp=0xc024009488 pc=0x4c7a328

goroutine 4 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x5be8220)
	pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:882 +0x8b
created by github.com/golang/glog.init.0
	pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:410 +0x272

goroutine 35 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:139 +0x9f
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 51 [chan receive]:
github.com/moby/buildkit/util/appcontext.Context.func1.1(0xc000052cc0, 0xc00043c260, 0xc000256320)
	pkg/mod/github.com/hinshun/buildkit@v0.0.0-20200128194027-9973cb02a5b6/util/appcontext/appcontext.go:30 +0x38
created by github.com/moby/buildkit/util/appcontext.Context.func1
	pkg/mod/github.com/hinshun/buildkit@v0.0.0-20200128194027-9973cb02a5b6/util/appcontext/appcontext.go:28 +0xff

goroutine 52 [select]:
google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc000388480)
	pkg/mod/google.golang.org/grpc@v1.28.0/balancer_conn_wrappers.go:69 +0xc1
created by google.golang.org/grpc.newCCBalancerWrapper
	pkg/mod/google.golang.org/grpc@v1.28.0/balancer_conn_wrappers.go:60 +0x16f

goroutine 53 [chan receive]:
google.golang.org/grpc.(*addrConn).resetTransport(0xc00033a000)
	pkg/mod/google.golang.org/grpc@v1.28.0/clientconn.go:1155 +0x60d
created by google.golang.org/grpc.(*addrConn).connect
	pkg/mod/google.golang.org/grpc@v1.28.0/clientconn.go:798 +0xc2

goroutine 54 [select]:
github.com/moby/buildkit/util/progress/progressui.DisplaySolveStatus(0x51bee80, 0xc000388500, 0x0, 0x0, 0x0, 0x0, 0x518b540, 0xc000010010, 0xc0002f4300, 0x0, ...)
	pkg/mod/github.com/hinshun/buildkit@v0.0.0-20200128194027-9973cb02a5b6/util/progress/progressui/display.go:55 +0x3b8
github.com/docker/buildx/util/progress.NewPrinter.func1(0xc000010010, 0x4fbdc49, 0x5, 0x51bee80, 0xc000388500, 0xc0002f4300, 0xc0003967c0, 0xc0002f4360)
	pkg/mod/github.com/docker/buildx@v0.3.1/util/progress/printer.go:52 +0x9c
created by github.com/docker/buildx/util/progress.NewPrinter
	pkg/mod/github.com/docker/buildx@v0.3.1/util/progress/printer.go:46 +0x15c

goroutine 55 [chan receive]:
github.com/openllb/hlb/solver.NewProgress.func1(0x0, 0x0)
	/go/src/hlb/solver/progress.go:107 +0x7f
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0000bfa10, 0xc000396800)
	pkg/mod/golang.org/x/sync@v0.0.0-20190423024810-112230192c58/errgroup/errgroup.go:57 +0x57
created by golang.org/x/sync/errgroup.(*Group).Go
	pkg/mod/golang.org/x/sync@v0.0.0-20190423024810-112230192c58/errgroup/errgroup.go:54 +0x66

goroutine 56 [semacquire]:
sync.runtime_Semacquire(0xc0000bfa50)
	/usr/local/go/src/runtime/sema.go:56 +0x39
sync.(*WaitGroup).Wait(0xc0000bfa48)
	/usr/local/go/src/sync/waitgroup.go:130 +0x65
golang.org/x/sync/errgroup.(*Group).Wait(0xc0000bfa40, 0x0, 0x0)
	pkg/mod/golang.org/x/sync@v0.0.0-20190423024810-112230192c58/errgroup/errgroup.go:40 +0x31
github.com/docker/buildx/util/progress.NewMultiWriter.func1(0xc0002f43c0, 0xc0000bfa40, 0x51b29c0, 0xc0003967c0)
	pkg/mod/github.com/docker/buildx@v0.3.1/util/progress/multiwriter.go:90 +0x42
created by github.com/docker/buildx/util/progress.NewMultiWriter
	pkg/mod/github.com/docker/buildx@v0.3.1/util/progress/multiwriter.go:88 +0xdf

goroutine 57 [chan receive]:
github.com/openllb/hlb/solver.NewProgress.func2(0x0, 0x0)
	/go/src/hlb/solver/progress.go:120 +0xaa
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0000bfa10, 0xc000396820)
	pkg/mod/golang.org/x/sync@v0.0.0-20190423024810-112230192c58/errgroup/errgroup.go:57 +0x57
created by golang.org/x/sync/errgroup.(*Group).Go
	pkg/mod/golang.org/x/sync@v0.0.0-20190423024810-112230192c58/errgroup/errgroup.go:54 +0x66

goroutine 58 [select]:
github.com/docker/buildx/util/progress.(*MultiWriter).WithPrefix.func1(0x8, 0x501f520)
	pkg/mod/github.com/docker/buildx@v0.3.1/util/progress/multiwriter.go:31 +0x382
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0000bfa40, 0xc0003885c0)
	pkg/mod/golang.org/x/sync@v0.0.0-20190423024810-112230192c58/errgroup/errgroup.go:57 +0x57
created by golang.org/x/sync/errgroup.(*Group).Go
	pkg/mod/golang.org/x/sync@v0.0.0-20190423024810-112230192c58/errgroup/errgroup.go:54 +0x66

goroutine 12 [select]:
github.com/docker/buildx/util/progress.(*MultiWriter).WithPrefix.func1(0x8, 0x501f520)
	pkg/mod/github.com/docker/buildx@v0.3.1/util/progress/multiwriter.go:31 +0x382
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0000bfa40, 0xc0004594c0)
	pkg/mod/golang.org/x/sync@v0.0.0-20190423024810-112230192c58/errgroup/errgroup.go:57 +0x57
created by golang.org/x/sync/errgroup.(*Group).Go
	pkg/mod/golang.org/x/sync@v0.0.0-20190423024810-112230192c58/errgroup/errgroup.go:54 +0x66

goroutine 44 [IO wait]:
internal/poll.runtime_pollWait(0x651dd88, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc00043e258, 0x72, 0x8001, 0x8000, 0xffffffffffffffff)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc00043e240, 0xc000286000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x1f2
os.(*File).read(...)
	/usr/local/go/src/os/file_unix.go:263
os.(*File).Read(0xc0000cc030, 0xc000286000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/os/file.go:108 +0x70
io.copyBuffer(0x5189600, 0xc0003fa0e0, 0x518b520, 0xc0000cc030, 0xc000286000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:402 +0x122
io.Copy(...)
	/usr/local/go/src/io/io.go:364
os/exec.(*Cmd).writerDescriptor.func1(0x0, 0x0)
	/usr/local/go/src/os/exec/exec.go:288 +0x63
os/exec.(*Cmd).Start.func1(0xc00011a000, 0xc0003fa140)
	/usr/local/go/src/os/exec/exec.go:409 +0x27
created by os/exec.(*Cmd).Start
	/usr/local/go/src/os/exec/exec.go:408 +0x58f

goroutine 45 [select]:
os/exec.(*Cmd).Start.func2(0xc00011a000)
	/usr/local/go/src/os/exec/exec.go:416 +0xc4
created by os/exec.(*Cmd).Start
	/usr/local/go/src/os/exec/exec.go:415 +0x62d

goroutine 66 [IO wait]:
internal/poll.runtime_pollWait(0x651df28, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc00043e198, 0x72, 0x8001, 0x8000, 0xffffffffffffffff)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc00043e180, 0xc00027e000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x1f2
os.(*File).read(...)
	/usr/local/go/src/os/file_unix.go:263
os.(*File).Read(0xc0000cc018, 0xc00027e000, 0x8000, 0x8000, 0x0, 0x10401, 0x0)
	/usr/local/go/src/os/file.go:108 +0x70
github.com/docker/cli/cli/connhelper/commandconn.(*commandConn).Read(0xc000118000, 0xc00027e000, 0x8000, 0x8000, 0xc006000030, 0x30, 0x28)
	pkg/mod/github.com/docker/cli@v0.0.0-20190523191156-ab688a9a79a1/cli/connhelper/commandconn/commandconn.go:196 +0x56
bufio.(*Reader).Read(0xc00043e420, 0xc0004d4e38, 0x9, 0x9, 0xc0004e2000, 0x6151d98, 0x0)
	/usr/local/go/src/bufio/bufio.go:223 +0x23e
io.ReadAtLeast(0x51890e0, 0xc00043e420, 0xc0004d4e38, 0x9, 0x9, 0x9, 0x459fb49, 0xc006000030, 0xc006000004)
	/usr/local/go/src/io/io.go:310 +0x88
io.ReadFull(...)
	/usr/local/go/src/io/io.go:329
golang.org/x/net/http2.readFrameHeader(0xc0004d4e38, 0x9, 0x9, 0x51890e0, 0xc00043e420, 0x0, 0x0, 0xc006000030, 0x0)
	pkg/mod/golang.org/x/net@v0.0.0-20190620200207-3b0461eec859/http2/frame.go:237 +0x88
golang.org/x/net/http2.(*Framer).ReadFrame(0xc0004d4e00, 0xc006000030, 0xc006000000, 0x0, 0x0)
	pkg/mod/golang.org/x/net@v0.0.0-20190620200207-3b0461eec859/http2/frame.go:492 +0xa1
google.golang.org/grpc/internal/transport.(*http2Client).reader(0xc00015a000)
	pkg/mod/google.golang.org/grpc@v1.28.0/internal/transport/http2_client.go:1270 +0x170
created by google.golang.org/grpc/internal/transport.newHTTP2Client
	pkg/mod/google.golang.org/grpc@v1.28.0/internal/transport/http2_client.go:300 +0xcf0

goroutine 82 [select]:
google.golang.org/grpc/internal/transport.(*controlBuffer).get(0xc0004cfb30, 0x1, 0x0, 0x0, 0x0, 0x0)
	pkg/mod/google.golang.org/grpc@v1.28.0/internal/transport/controlbuf.go:395 +0x107
google.golang.org/grpc/internal/transport.(*loopyWriter).run(0xc0005d6000, 0x0, 0x0)
	pkg/mod/google.golang.org/grpc@v1.28.0/internal/transport/controlbuf.go:513 +0x1b6
google.golang.org/grpc/internal/transport.newHTTP2Client.func3(0xc00015a000)
	pkg/mod/google.golang.org/grpc@v1.28.0/internal/transport/http2_client.go:346 +0x7b
created by google.golang.org/grpc/internal/transport.newHTTP2Client
	pkg/mod/google.golang.org/grpc@v1.28.0/internal/transport/http2_client.go:344 +0xea8
```

### PR DESCRIPTION
**Pull request by coryb**
fixes #52 

I ended up needing this fixed to work though some testing on #51, so submitting this first.  

Basically I ended up caching the llb.State at the time of the alias definition, then looking that up late rather than attempting to regenerate the llb.State every time the alias is used (causing the infinite recursion when used within the same fs). 

I also removed the aliasCallback, it seemed unnecessary except for the one case where we were trying to lookup to alias results, which I solved by moving the cache into the codegen struct.

### CODE REVIEW

File: codegen/decl.go [hunk 1]
```diff
@@ -42,51 +42,49 @@ func (cg *CodeGen) EmitFuncDecl(ctx context.Context, scope *parser.Scope, fun *p
...
 }
 
 func (cg *CodeGen) EmitAliasDecl(ctx context.Context, scope *parser.Scope, alias *parser.AliasDecl, call *parser.CallStmt) (interface{}, error) {
-	var v interface{}
-	_, err := cg.EmitFuncDecl(ctx, scope, alias.Func, call, "", func(aliasCall *parser.CallStmt, aliasValue interface{}) {
-		if alias.Call == aliasCall {
-			v = aliasValue
-		}
-	})
+	if v, ok := cg.aliasCache.Load(alias.Call); ok {
```
Comment (hinshun) [inline codegen/decl.go]: I'm not sure this is correct? What about aliases that have arguments? The cache key also needs to consider the `call.Args`.

Consider:
```hlb
fs foo(string command) {
    image "alpine"
    run string {
        format "%s > /out/foo" command
    } with option {
        dir "/src"
        mount fs { scratch; } "/out" as fooOut
}

fs default() {
    scratch
    copy fs { fooOut "echo hello"; } "/foo" "/foo1"
    copy fs { fooOut "echo world"; } "/foo" "/foo2"
}
```

The second time `fooOut` is called, the `llb.State` is cached in `aliasCache`, so both `/foo1` and `/foo2` have the content `hello`.

Comment (coryb) [reply codegen/decl.go]: Ughh, yeah, I will rethink this.

**Comment by coryb** [comment]
@hinshun I tried a different approach and it seems to work better.  I modified the aliasCallback signature to return a bool which indicates if we should continue processing the block or return.  Now the callback used in `EmitAliasDecl` can return a `false` when the desired alias has been found which will cause the block to stop being processed to prevent infinite recursion.

Tried your example, and it seems to work as well:
```
fs foo(string command) {
    image "alpine"
    run string {
        format "%s > /out/foo" command
    } with option {
        dir "/src"
        mount fs { scratch; } "/out" as fooOut
    }
}

fs test() {
    scratch
    copy fs { fooOut "echo hello"; } "/foo" "/foo1"
    copy fs { fooOut "echo world"; } "/foo" "/foo2"
	output with option {
		download "./test/"
	}
}
```
```
$ ./hlb run -t test ./source.hlb
[+] Building 0.6s (7/7) FINISHED
 => compiling [test]                                          0.0s
 => docker-image://docker.io/library/alpine:latest            0.5s
 => => resolve docker.io/library/alpine:latest                0.5s
 => CACHED /bin/sh -c echo hello > /out/foo                   0.0s
 => CACHED copy /foo /foo1                                    0.0s
 => CACHED /bin/sh -c echo world > /out/foo                   0.0s
 => CACHED copy /foo /foo2                                    0.0s
 => exporting to client                                       0.0s
 => => copying files 68B                                      0.0s
```

```
$ cat ./test/foo1
hello
$ cat ./test/foo2
world
```
